version: '3'
services:
  springboot-app:
#    container_name: spring-app
    image: springbooot-app
    build: .
    ports:
      - 8090-8100:8080

  mysqldb:
    container_name: mysqldb
    image: mysql
    ports:
      - 3307:3306
    environment:
        MYSQL_DATABASE: test
        MYSQL_ROOT_PASSWORD: root